webserver_log_file = "webserver.log"
manage_log_file = "manage.log"
scheduler_log_file = ""
log_level = "INFO"
worker_hashrate_fold = 86400
stage = false

site_title = "Simple Coin Multi"
# the FQDN
site_url = "http://www.simplecoinmulti.com"
# host for static assets e.g. {assets_address}/css/main.css
assets_address = "/static"
# logo img
logo = "/img/logo.png"
site_meta_desc = "A custom mining pool with automatic exchanging between currencies, no registration, and a focus on developing new tools for miners"
# Default values for new miner config
default_stratum_url = "stratum+tcp://stratum.simplecoinmulti.com"
default_stratum_port = "3333"
charge_autoex_fees = false

# i18n/localisation configuration
# =======================================================================
default_locale = "en"

# acceptable locales that we have translations for
[available_locales]
en = "English"
# zh_Hans_CN = "\u5B98\u8A71"
# ja = "\u65E5\u672C\u8A9E"


[main_cache]
type = "redis"

[redis_conn]
type = "redis"

[chains.default]
currencies = []
safety_margin = 2

[mining_servers.default]
display = true

[currencies.default]
buyable = false
sellable = false
mineable = false
merged = false
trans_confirmations = 6
block_mature_confirms = 120

[currencies.BTC]
name = "Bitcoin"
algo = "sha256"
address_version = [0, 5]
block_time = 120

[currencies.RBY]
name = "Rubycoin"
algo = "scrypt"
address_version = [61]
block_time = 150

[currencies.BTM]
name = "Bitmark"
algo = "scrypt"
address_version = [85]
block_time = 120
block_mature_confirms = 720

[currencies.DRK]
name = "Darkcoin"
algo = "x11"
address_version = [76]
block_time = 120

[currencies.URO]
name = "Urocoin"
algo = "x11"
address_version = [68]
block_time = 120

[currencies.DOGE]
name = "Dogecoin"
algo = "scrypt"
address_version = [30]
merged = true
block_time = 60
block_explore = "https://dogechain.info/block/"
tx_explore = "https://dogechain.info/tx/"

[currencies.SYS]
name = "Syscoin"
algo = "scrypt"
address_version = [63]
merged = true
block_time = 60

[currencies.PTC]
name = "Pesetacoin"
algo = "scrypt"
address_version = [47]
merged = true
block_time = 60

[currencies.TCO]
name = "Tacocoin"
algo = "scrypt"
address_version = [48]
merged = true
block_time = 60

[currencies.ULTC]
name = "Umbrella-LTC"
algo = "scrypt"
address_version = [68]
merged = true
block_time = 600

[currencies.LTC]
name = "Litecoin"
algo = "scrypt"
address_version = [48]
block_time = 600
block_explore = "http://qukuai.com/ltc/block/"
tx_explore = "http://qukuai.com/ltc/tx/"

[currencies.VTC]
name = "Vertcoin"
algo = "lyra2re"
address_version = [71]
block_time = 150

[currencies.MRY]
name = "Murraycoin"
algo = "scryptn"
address_version = [50]
block_time = 100

[currencies.SPA]
name = "Spaincoin"
algo = "scryptn"
address_version = [63]
block_time = 120

[currencies.EXE]
name = "Execoin"
algo = "scryptn"
address_version = [33]
block_time = 45

[currencies.MON]
name = "Monocle"
algo = "scryptn"
address_version = [50]
merged = true
block_time = 120

[currencies.GRE]
name = "Greencoin"
algo = "scrypt"
address_version = [38]
merged = true
block_time = 60

[currencies.FRAC]
name = "Fractalcoin"
algo = "x11"
address_version = [36]
block_time = 60

[currencies.START]
name = "Startcoin V2"
algo = "x11"
address_version = [125]
block_time = 60

[currencies.CANN]
name = "Cannabiscoin"
algo = "x11"
address_version = [28]
block_time = 42

[currencies.VIA]
name = "Viacoin"
algo = "scrypt"
address_version = [71]
merged = true
block_time = 24
block_mature_confirms = 3600

[currencies.FTC]
name = "Feathercoin"
algo = "scrypt"
address_version = [14]
block_time = 60

[currencies.WDC]
name = "Worldcoin"
algo = "scrypt"
address_version = [73]
block_time = 30

[currencies.ANC]
name = "Anoncoin"
algo = "scrypt"
address_version = [23]
block_time = 205

[currencies.MEC]
name = "Megacoin"
algo = "scrypt"
address_version = [50]
block_time = 150

[currencies.EMC2]
name = "Einsteiniumcoin"
algo = "scrypt"
address_version = [33]
block_time = 60

[currencies.ZVTC]
name = "ZeroVertcoin"
algo = "scryptn"
merged = true
address_version = [82]
block_time = 150

[currencies.NVC]
name = "Novacoin"
algo = "scrypt"
address_version = [8]
block_time = 600

[currencies.POT]
name = "Potcoin"
algo = "scrypt"
address_version = [55]
block_time = 40
block_mature_confirms = 260

[currencies.AUR]
name = "Auroracoin"
algo = "scrypt"
address_version = [23]
block_time = 300
block_mature_confirms = 100

[currencies.TAG]
name = "Tagcoin"
algo = "scrypt"
address_version = [65]
block_time = 240

[currencies.NOBL]
name = "Noblecoin"
algo = "scrypt"
address_version = [21]
block_time = 60

[currencies.EXCL]
name = "Exclusivecoin"
algo = "x11"
address_version = [33]
block_time = 40

[currencies.CKC]
name = "Checkcoin"
algo = "x11"
address_version = [28]
block_time = 150

[currencies.GLD]
name = "Goldcoin"
algo = "scrypt"
address_version = [32]
block_time = 120

# Tasks
# =========================================
# All "task" entries configure when functions in scheduler.py get run.
# Description of the tasks purpose can be found in scheduler.py Time periods
# that are not defined are implied to be "*". So omitting "minute" will run the
# task every minute.
[[tasks]]
name = "compress_slices"
enabled = true
minute = "0,15,30,45"
second = 35

[[tasks]]
name = "generate_credits"
enabled = true
second = 55

[[tasks]]
name = "create_trade_req"
enabled = true
args = ["sell"]
minute = 1
hour = "*/4"

[[tasks]]
name = "create_trade_req"
enabled = true
args = ["buy"]
minute = 2
hour = "*/6"

[[tasks]]
name = "collect_minutes"
enabled = true
second = 35

[[tasks]]
name = "collect_ppagent_data"
enabled = true
second = 40

[[tasks]]
name = "compress_minute"
enabled = true
minute = "*/5"
second = 20

[[tasks]]
name = "compress_five_minute"
enabled = true
minute = 2
second = 2

[[tasks]]
name = "update_block_state"
enabled = true
minute = "*/2"

[[tasks]]
name = "update_online_workers"
enabled = true
minute = "*/5"
second = 30

[[tasks]]
name = "cache_user_donation"
enabled = true
minute = "*/15"
second = 15

[[tasks]]
name = "update_network"
enabled = true
second = 20

[[tasks]]
name = "server_status"
enabled = true
second = 15

[[tasks]]
name = "leaderboard"
enabled = true
minute = "*/5"
second = 40

[[tasks]]
name = "cache_profitability"
enabled = true
second = 0
minute = 8
hour = "*/3"

# Algorithms
# =========================================
[algos.x11]
hashes_per_share = 4294967296
normalize_mult = 0.181818182
display = "X11"

[algos.sha256]
hashes_per_share = 4294967296
normalize_mult = 1
display = "SHA256"

[algos.scryptn]
hashes_per_share = 65536
normalize_mult = 2.127659574
display = "Scrypt-N"

[algos.scrypt]
hashes_per_share = 65536
normalize_mult = 1
display = "Scrypt"

[algos.lyra2re]
hashes_per_share = 33554432
normalize_mult = 1
display = "Lyra2RE"

[[navbar.left_nav]]
title = "Home"
icon = "home"
link = "/"
active_key = "home"

[[navbar.left_nav]]
title = "Getting Started"
icon = "cog"
link = "/configuration_guide"
active_key = "config"

[[navbar.left_nav]]
title = "User Stats"
icon = "user"
link = "/stats"
active_key = "stats"

[[navbar.left_nav]]
title = "Pool Stats"
icon = "life-ring"
link = "/pool_stats"
active_key = "pool_stats"

[[navbar.left_nav]]
title = "Leaderboard"
icon = "bar-chart-o"
link = "/leaderboard"
active_key = "leaderboard"

[[navbar.left_nav]]
title = "Extras"
icon = "star"
link = "#"
active_key = ""
[[navbar.left_nav.dropdown]]
title = "Simple Crypto Website"
icon = "globe"
link = "http://www.simplecryptogroup.com"
[[navbar.left_nav.dropdown]]
title = "Source Code"
icon = "github"
link = "http://www.github.com/simplecrypto/simplecoin_multi"

[[navbar.right_nav]]
title = "Contact Us"
icon = "bullhorn"
link = "#"
active_key = ""
[[navbar.right_nav.dropdown]]
title = "Email"
icon = "envelope"
link = "mailto:simplecryptogroup@gmail.com"
[[navbar.right_nav.dropdown]]
title = "Simple Crypto Website"
icon = "globe"
link = "http://www.simplecryptogroup.com"
[[navbar.right_nav.dropdown]]
title = "IRC"
icon = "comments"
link = "https://kiwiirc.com/client/irc.freenode.net/#simplecrypto"
[[navbar.right_nav.dropdown]]
title = "Reddit"
icon = "reddit"
link = "http://www.reddit.com/r/simplecrypto"
[[navbar.right_nav.dropdown]]
title = "Github"
icon = "github"
link = "http://www.github.com/simplecrypto/"
