pool_payout_currency = "BTC"
SECRET_KEY = "somethting_really_secret"
SQLALCHEMY_DATABASE_URI = "sqlite://"
DEBUG = true
rpc_signature = "test"

[redis_conn]
type = "mock_redis"

[main_cache]
type = "mock_redis"

[chains.2]
title = "Vertcoin"
algo = "scryptn"
type = "prop"
last_n = 2
fee_perc = "0.01"

[chains.1]
title = "Vertcoin"
algo = "scryptn"
type = "pplns"
last_n = 2
fee_perc = "0.01"

[locations.CA]
location_acronym = "CA"
location = "Beauharnois, Canada"
country_flag = "/img/ca.svg"

[currencies.BTC]
exchangeable = true
pool_payout_addr = "1LmZN5ifbHdQy5jW9wNqyTuke3odY2Zos8"

[currencies.TCO]
mineable = true
pool_payout_addr = "LUMPrhhWnoTfNXnDNWyqGG355fjTUVzFYX"

[currencies.DOGE]
exchangeable = true
mineable = true

[mining_servers.1]
address = "localhost"
monitor_address = "http://localhost:3855/stratum"
port = 3333
location = "CA"
diff = 512
chain = "1"
